USE   REST_ASP_NET_UDEMY;
CREATE TABLE PERSON (
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
ADDRESS VARCHAR(100) NOT NULL,
FIRST_NAME VARCHAR(80) NOT NULL,
LAST_NAME VARCHAR(80) NOT NULL,
GENDER VARCHAR(6) NOT NULL,
PRIMARY kEY (ID)
)